apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: on6clb89t-go
  janus-idp.io/tekton: on6clb89t-go
  backstage.io/kubernetes-id: on6clb89t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: on6clb89t-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
